version: '3.8'
services:
  back-end:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"
  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
      - back-end
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end